In [47]:
import numpy as np

def optimal_parenthisezation(s, i, j):
    if i == j:
        print(f"A{i + 1}", end="")
    else:
        print("(", end="")
        optimal_parenthisezation(s, i, s[i][j])
        optimal_parenthisezation(s, s[i][j] + 1, j)
        print(")", end="")

def matrix_chain_order(p):
    n = len(p) - 1
    m = np.zeros((n, n))
    s = np.zeros((n, n), dtype=int)
    for l in range(2, n + 1):
        for i in range(n - l + 1):
            j = i + l - 1
            m[i, j] = float("inf")
            for k in range(i, j):
                q = m[i, k] + m[k + 1, j] + p[i] * p[k + 1] * p[j + 1]
                if q < m[i, j]:
                    m[i, j] = q
                    s[i, j] = k
    return m, s


p = [5, 10, 3, 12, 5, 50, 6]
m, s = matrix_chain_order(p)
optimal_parenthisezation(s, 0, len(p) - 2)
print()
print(m)
print(s)

((A1A2)((A3A4)(A5A6)))
[[   0.  150.  330.  405. 1655. 2010.]
 [   0.    0.  360.  330. 2430. 1950.]
 [   0.    0.    0.  180.  930. 1770.]
 [   0.    0.    0.    0. 3000. 1860.]
 [   0.    0.    0.    0.    0. 1500.]
 [   0.    0.    0.    0.    0.    0.]]
[[0 0 1 1 3 1]
 [0 0 1 1 1 1]
 [0 0 0 2 3 3]
 [0 0 0 0 3 3]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]]
